name: Auto update

# Run only manually for now
# todo: automate updates for SDL3 releases 
on: [ workflow_dispatch ]

jobs:
  build-dockerfile:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/miwwa/sdl3-gen:latest
          cache-from: type=registry,ref=ghcr.io/miwwa/sdl3-gen:buildcache
          cache-to: type=registry,ref=ghcr.io/miwwa/sdl3-gen:buildcache,mode=max
  
  generate:
    name: Generate bindings
    runs-on: ubuntu-latest
    needs: [ build-dockerfile ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update SDL submodule
        run: git submodule update --remote SDL
      - name: Generate sources
        run: docker run --rm -v .:/app -w /app --name sdl3-cs ghcr.io/miwwa/sdl3-gen:latest
      - uses: actions/upload-artifact@v4
        with:
          name: sdl3-gen
          path: |
            SDL3
            GenerateBindings
  
  build-lib:
    name: Build lib
    runs-on: ubuntu-latest
    needs: [ generate ]
    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sdl3-gen

      - name: Display structure of downloaded files
        run: ls -R

      - name: dotnet build GenerateBindings
        run: dotnet build GenerateBindings -c Release

      - name: msbuild SDL3
        run: msbuild -restore SDL3-CS.Legacy.sln /p:Configuration=Release

      - name: dotnet build SDL3.Core
        run: dotnet build SDL3/SDL3.Core.csproj -c Release

  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs: [ generate ]
    steps:
      - uses: actions/checkout@v4
      
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: update SDL
          title: [Automatic] Update SDL
          branch: sdl-update
          delete-branch: true
          body: |
            Automatic SDL bindings update