name: Auto update

# Run only manually for now
# todo: automate updates for SDL3 releases 
on: [ workflow_dispatch ]

jobs:
  generate:
    name: Generate bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update SDL submodule
        run: git submodule update --remote SDL
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: miwwa/sdl3-gen:latest
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max
      - name: Generate sources
        run: docker run --rm -v .:/app -w /app --name sdl3-cs miwwa/sdl3-gen:latest
  
  build:
    name: Build lib
    runs-on: ubuntu-latest
    needs: [ generate ]
    steps:
      - uses: actions/checkout@v4
      - name: dotnet build GenerateBindings
        run: dotnet build GenerateBindings -c Release
      - name: msbuild SDL3
        run:  msbuild -restore SDL3-CS.Legacy.sln /p:Configuration=Release
      - name: dotnet build SDL3.Core
        run: dotnet build SDL3/SDL3.Core.csproj -c Release
